name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  verify:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test & build
        run: |
          npm ci
          npm test -- core
          npm run test:e2e
          npm run build -- core
      - env:
          CI: true
